// REQUIRES Shaders/ShaderHeaders/Version.comp
// REQUIRES Shaders/ShaderHeaders/ComputeShaderWorkGroupSizes.comp
// REQUIRES Shaders/ShaderHeaders/SsboBufferBindings.comp
// REQUIRES Shaders/ShaderHeaders/CrossShaderUniformLocations.comp
// REQUIRES Shaders/Compute/Collisions/PositionToMortonCode.comp
// REQUIRES Shaders/Compute/Collisions/ParticleParticle/Buffers/ParticleSortingDataBuffer.comp
// REQUIRES Shaders/Compute/ParticleBuffer.comp


// Y and Z work group sizes default to 1
layout (local_size_x = WORK_GROUP_SIZE_X) in;

/*------------------------------------------------------------------------------------------------
Description:
    Generates a Morton Code for the current thread's particle's position.
Parameters: None
Returns:    None
Creator:    John Cox, 5/2017
------------------------------------------------------------------------------------------------*/
void main()
{
    uint threadIndex = gl_GlobalInvocationID.x;
    if (threadIndex >= uMaxNumParticles) // or uMaxNumParticleSortingData
    {
        return;
    }

    uint mortonCode = PositionToMortonCode(AllParticles[threadIndex]._currPos);
    if (AllParticles[threadIndex]._isActive == 0)
    {
        // sort inactive particles to the back by giving them a large sorting value
        mortonCode = 0xffffffff;
    }

    AllParticleSortingData[threadIndex]._sortingData = mortonCode;
    AllParticleSortingData[threadIndex]._preSortedIndex = int(threadIndex);
}
