// REQUIRES Shaders/ShaderHeaders/SsboBufferBindings.comp
// REQUIRES Shaders/ShaderHeaders/CrossShaderUniformLocations.comp
// REQUIRES Shaders/Compute/GeometryStuff/BoundingBox.comp


uniform uint uParticleBoundingBoxGeometryBufferSize;

/*-----------------------------------------------------------------------------------------------
Description:
    The SSBO that will contain all the vertices necessary to draw a bounding box for each 
    particle's collision radius.
Creator:    John Cox, 6/2017
-----------------------------------------------------------------------------------------------*/
layout (std430, binding = PARTICLE_BOUNDING_BOX_GEOMETRY_BUFFER_BINDING) buffer ParticleBoundingBoxGeometryBuffer
{
    BoundingBox AllParticleBoundingBoxes[];
};