// REQUIRES Shaders/ShaderHeaders/SsboBufferBindings.comp
// REQUIRES Shaders/ShaderHeaders/CrossShaderUniformLocations.comp


layout(location = UNIFORM_LOCATION_ALL_PREFIX_SUMS_SIZE) uniform uint uMaxPrefixSums;

/*------------------------------------------------------------------------------------------------
Description:
    Will be filled with 0s and 1s (bit values extracted from the numbers being sorted).
    See explanation of sizes in PrefixSumSsbo.

    Note: The totalNumberOfOnes is used along with uPrefixSumsMaxEntries in 
    SortSortingDataWithPrefixSums.comp to determine the offset for the 1s.
Creator:    John Cox, 7/2017
------------------------------------------------------------------------------------------------*/
layout (std430, binding = PREFIX_SCAN_BUFFER_BINDING) buffer PrefixScanBuffer
{
    uint totalNumberOfOnes;
    uint AllPrefixSums[];
};

