// REQUIRES Shaders/ShaderHeaders/SsboBufferBindings.comp
// REQUIRES Shaders/ShaderHeaders/CrossShaderUniformLocations.comp
// REQUIRES Shaders/Compute/Collisions/BvhNode.comp


// see description of ParticleBvhNodeBuffer for detail
uniform uint uParticleBvhNumberLeaves;
uniform uint uParticleBvhNumberInternalNodes;
uniform uint uParticleBvhNodeBufferSize;

/*-----------------------------------------------------------------------------------------------
Description:
    The SSBO that will contain all nodes necessary for the internal nodes and the leaf nodes of 
    the BVH.

    The number of internal nodes shall be #particles - 1;
    The number of leaf nodes shall be #particles.
Creator:    John Cox, 5/2017
-----------------------------------------------------------------------------------------------*/
layout (std430, binding = PARTICLE_BVH_NODE_BUFFER_BINDING) buffer ParticleBvhNodeBuffer
{
    // leaf nodes first, then internal nodes 
    BvhNode AllBvhNodes[];
};


