// REQUIRES Shaders/ShaderHeaders/SsboBufferBindings.comp
// REQUIRES Shaders/ShaderHeaders/CrossShaderUniformLocations.comp
// REQUIRES Shaders/Compute/GeometryStuff/Box2D.comp


uniform uint uCollidableGeometryBoundingBoxGeometryBufferSize;

/*-----------------------------------------------------------------------------------------------
Description:
    The SSBO that will contain all the vertices necessary to draw a bounding box for each 
    polygon's collision box.
Creator:    John Cox, 7/2017
-----------------------------------------------------------------------------------------------*/
layout (std430, binding = COLLIDABLE_GEOMETRY_BOUNDING_BOX_GEOMETRY_BUFFER_BINDING) buffer CollidableGeometryBoundingBoxGeometryBuffer
{
    Box2D AllCollidableGeometryBoundingBoxes[];
};
