// REQUIRES Shaders/ShaderHeaders/SsboBufferBindings.comp
// REQUIRES Shaders/ShaderHeaders/CrossShaderUniformLocations.comp
// REQUIRES Shaders/Compute/Collisions/SortingData.comp


// expected to be the size of uMaxCollidablePolygons
uniform uint uMaxNumCollidablePolygonSortingData;

// these are swapped on each loop of the parallel sort routine
layout(location = UNIFORM_LOCATION_COLLIDABLE_POLYGON_SORTING_DATA_BUFFER_READ_OFFSET) uniform uint uCollidablePolygonSortingDataBufferReadOffset;
layout(location = UNIFORM_LOCATION_COLLIDABLE_POLYGON_SORTING_DATA_BUFFER_WRITE_OFFSET) uniform uint uCollidablePolygonSortingDataBufferWriteOffset;

/*------------------------------------------------------------------------------------------------
Description:
    See description in ParticleSortingDataSsbo.h.

    Will be 2x the size of uMaxCollidablePolygons.

    Identical in contents and concept to ParticleSortingDataBuffer, but OpenGL compute shaders 
    must refer to buffers explicitly by name, so different buffers need differnet names.
Creator:    John Cox, 7/2017
------------------------------------------------------------------------------------------------*/
layout (std430, binding = COLLIDABLE_POLYGON_SORTING_DATA_BUFFER_BINDING) buffer CollidablePolygonSortingDataBuffer
{
    SortingData AllCollidablePolygonSortingData[];
};
