// REQUIRES Shaders/ShaderHeaders/SsboBufferBindings.comp
// REQUIRES Shaders/ShaderHeaders/CrossShaderUniformLocations.comp
// REQUIRES Shaders/Compute/Collisions/SortingData.comp


// expected to be the size of uMaxCollidablePolygons
uniform uint uMaxNumGeometrySortingData;

// these are swapped on each loop of the parallel sort routine
layout(location = UNIFORM_LOCATION_COLLIDABLE_GEOMETRY_SORTING_DATA_BUFFER_READ_OFFSET) uniform uint uCollidableGeometrySortingDataBufferReadOffset;
layout(location = UNIFORM_LOCATION_COLLIDABLE_GEOMETRY_SORTING_DATA_BUFFER_WRITE_OFFSET) uniform uint uCollidableGeometrySortingDataBufferWriteOffset;

/*------------------------------------------------------------------------------------------------
Description:
    See description in ParticleSortingDataSsbo.h.

    Will be 2x the size of uMaxCollidablePolygons.

    Identical in contents and concept to ParticleSortingDataBuffer, but OpenGL compute shaders 
    must refer to buffers explicityly by name, so different buffers need differnet names.
Creator:    John Cox, 5/2017
------------------------------------------------------------------------------------------------*/
layout (std430, binding = COLLIDABLE_GEOMETRY_SORTING_DATA_BUFFER_BINDING) buffer CollidableGeometrySortingDataBuffer
{
    SortingData AllGeometrySortingData[];
};
