// REQUIRES Shaders/ShaderHeaders/SsboBufferBindings.comp
// REQUIRES Shaders/ShaderHeaders/CrossShaderUniformLocations.comp
// REQUIRES Shaders/Compute/Collisions/BvhNode.comp


uniform uint uGeometryBvhNumberLeaves;
uniform uint uGeometryBvhNumberInternalNodes;
uniform uint uGeometryBvhNodeBufferSize;

/*-----------------------------------------------------------------------------------------------
Description:
    The SSBO that will contain all nodes necessary for the internal nodes and the leaf nodes of 
    the BVH.

    Identical in contents and concept to ParticleBvhNodeBuffer, but OpenGL compute shaders must 
    refer to buffers explicitly by name, so different buffers need differnet names even if the 
    only difference is their size and data.
Creator:    John Cox, 7/2017
-----------------------------------------------------------------------------------------------*/
layout (std430, binding = GEOMETRY_BVH_NODE_BUFFER_BINDING) buffer GeometryBvhNodeBuffer
{
    // leaf nodes first, then internal nodes 
    BvhNode AllBvhNodes[];
};


