// REQUIRES Shaders/ShaderHeaders/SsboBufferBindings.comp
// REQUIRES Shaders/ShaderHeaders/CrossShaderUniformLocations.comp
// REQUIRES Shaders/Compute/GeometryStuff/PolygonFace.comp


uniform uint uMaxCollidablePolygons;

/*------------------------------------------------------------------------------------------------
Description:
    See description in CollidablePolygonSsbo.h.
Creator:    John Cox, 6/2017
------------------------------------------------------------------------------------------------*/
layout (std430, binding = COLLIDABLE_POLYGON_BUFFER_BINDING) buffer CollidablePolygonBuffer
{
    PolygonFace AllCollidablePolygons[];
};

