// REQUIRES Shaders/ShaderHeaders/SsboBufferBindings.comp
// REQUIRES Shaders/ShaderHeaders/CrossShaderUniformLocations.comp
// REQUIRES Shaders/Compute/GeometryStuff/PolygonFace.comp


uniform uint uMaxCollidablePolygons;

/*------------------------------------------------------------------------------------------------
Description:
    See description in CollidableGeometrySsbo.h.
Creator:    John Cox, 6/2017
------------------------------------------------------------------------------------------------*/
layout (std430, binding = COLLIDABLE_GEOMETRY_BUFFER_BINDING) buffer CollidableGeometryBuffer
{
    PolygonFace AllCollidableGeometry[];
};

