// REQUIRES Shaders/Compute/Collisions/MaxNumPotentialCollisions.comp

/*------------------------------------------------------------------------------------------------
Description:   
    Stores enough space for a single particle to have its own record about how many other 
    particles' bounding boxes overlapped with its own or how many collidable polygons it 
    overlapped.
Creator:    John Cox, 6/2017
------------------------------------------------------------------------------------------------*/
struct PotentialParticleCollisions
{
    int _numPotentialCollisions;

    // particle indexes for particle-particle collisions, polygon indexes for particle-polygon 
    // collisions
    int _objectIndexes[MAX_NUM_POTENTIAL_COLLISIONS];
};
