/*------------------------------------------------------------------------------------------------
Description:
    See description in SortingData.h.
Creator:    John Cox, 5/2017
------------------------------------------------------------------------------------------------*/
struct ParticleSortingData
{
    uint _sortingData;
    int _preSortedParticleIndex;

    // no GLSL-native structures, so no padding necessary on the CPU side
};
