// REQUIRES Shaders/Compute/GeometryStuff/PolygonFace.comp

/*-----------------------------------------------------------------------------------------------
Description:
    See Box2D.h for more detail.
Creator:    John Cox, 6/2017
-----------------------------------------------------------------------------------------------*/
struct Box2D
{
    PolygonFace _left;
    PolygonFace _right;
    PolygonFace _top;
    PolygonFace _bottom;

    // just using vec4's so everything is already aligned to 16bytes and no padding necessary
};