// REQUIRES Shaders/Compute/GeometryStuff/PolygonFace.comp

/*-----------------------------------------------------------------------------------------------
Description:
    See BoundingBox.h for more detail.

    Note: This is NOT to be confused with the BoundingBox structure of the same name in 
    BvhNodeBuffer.comp.  This one is meant for drawing.
Creator:    John Cox, 6/2017
-----------------------------------------------------------------------------------------------*/
struct Box2D
{
    PolygonFace _left;
    PolygonFace _right;
    PolygonFace _top;
    PolygonFace _bottom;

    // just using vec4's so everything is already aligned to 16bytes and no padding necessary
};